export const builtInActivities = [
  {
    id: "ceiling",
    emoji: "👀",
    title: "stare at the ceiling",
    desc: "notice a crack you've never named. give it a nickname if you want. or don't.",
    category: "still",
    vibe: "zero input, maximum presence",
  },
  {
    id: "clouds",
    emoji: "☁️",
    title: "watch clouds argue",
    desc: "find shapes. lose the shapes. forget what shapes are.",
    category: "outside",
    vibe: "sky television, no subscription",
  },
  {
    id: "water",
    emoji: "💧",
    title: "drink water like it's a ritual",
    desc: "one slow sip. hold it. swallow. you are a temple of hydration.",
    category: "tiny",
    vibe: "ceremony without meaning",
  },
  {
    id: "floor",
    emoji: "🫠",
    title: "lie on the floor",
    desc: "gravity is doing the work. you're just cooperating.",
    category: "still",
    vibe: "horizontal enlightenment",
  },
  {
    id: "pillow",
    emoji: "🛏️",
    title: "flip the pillow",
    desc: "find the cold side. press your cheek into it. time stops briefly.",
    category: "tiny",
    vibe: "small luxury, big peace",
  },
  {
    id: "window",
    emoji: "🪟",
    title: "open a window and listen",
    desc: "birds, cars, wind, someone's distant lawnmower. the world hums.",
    category: "senses",
    vibe: "ambient reality playlist",
  },
  {
    id: "tea",
    emoji: "🍵",
    title: "make tea and forget it",
    desc: "the ritual matters. drinking it is optional. warmth in a mug is enough.",
    category: "tiny",
    vibe: "process over outcome",
  },
  {
    id: "sock",
    emoji: "🧦",
    title: "find the comfiest sock",
    desc: "put it on your hand. puppet optional. judgment forbidden.",
    category: "weird",
    vibe: "domestic absurdism",
  },
  {
    id: "blink",
    emoji: "😌",
    title: "blink slowly, on purpose",
    desc: "like a very calm lizard who has never heard of email.",
    category: "still",
    vibe: "reptile energy",
  },
  {
    id: "shadow",
    emoji: "🌿",
    title: "sit in a patch of shade",
    desc: "the sun moved for you. or you moved for the sun. either way, nice.",
    category: "outside",
    vibe: "borrowed coolness",
  },
  {
    id: "smell",
    emoji: "🌸",
    title: "smell something nice",
    desc: "soap, rain, old book, clean laundry. let your nose do a tiny vacation.",
    category: "senses",
    vibe: "olfactory daydream",
  },
  {
    id: "stretch",
    emoji: "🐱",
    title: "stretch like a cat",
    desc: "no fitness goals. just spine noises and dignity optional.",
    category: "still",
    vibe: "feline wisdom",
  },
  {
    id: "hum",
    emoji: "🎵",
    title: "hum one note",
    desc: "hold it until it gets boring. boredom is the point.",
    category: "weird",
    vibe: "single-frequency meditation",
  },
  {
    id: "count",
    emoji: "🍃",
    title: "count five green things",
    desc: "plants, socks, mugs, envy — anything counts if you squint.",
    category: "outside",
    vibe: "gentle scavenger hunt",
  },
  {
    id: "breathe",
    emoji: "🫁",
    title: "breathe like you mean it",
    desc: "in for four, out for six. or don't count. your lungs know what to do.",
    category: "still",
    vibe: "autopilot appreciation",
  },
  {
    id: "hand",
    emoji: "✋",
    title: "look at your hands",
    desc: "weird little meat tools you've had your whole life. hi, hands.",
    category: "weird",
    vibe: "body inventory",
  },
  {
    id: "rain",
    emoji: "🌧️",
    title: "stand near rain without getting wet",
    desc: "doorway, window, porch. listen to the sound of not being outside.",
    category: "senses",
    vibe: "dry observation",
  },
  {
    id: "blanket",
    emoji: "🧣",
    title: "become a blanket burrito",
    desc: "wrap up. immobilize slightly. accept your new cylindrical form.",
    category: "tiny",
    vibe: "soft containment",
  },
  {
    id: "walk",
    emoji: "🚶",
    title: "walk with no destination",
    desc: "turn left because left felt right. arrive nowhere. success.",
    category: "outside",
    vibe: "purposeless pilgrimage",
  },
  {
    id: "pet",
    emoji: "🐾",
    title: "pet something soft",
    desc: "pet, pillow, plant, your own arm. all valid. all soft enough.",
    category: "tiny",
    vibe: "texture therapy",
  },
  {
    id: "dark",
    emoji: "🌙",
    title: "sit in dim light",
    desc: "not full darkness. just enough to feel like evening at any hour.",
    category: "senses",
    vibe: "perpetual golden hour",
  },
  {
    id: "exist",
    emoji: "✨",
    title: "exist aggressively",
    desc: "you are here. that is the whole activity. no notes.",
    category: "weird",
    vibe: "pure being",
  },
  {
    id: "rock",
    emoji: "🪨",
    title: "find a rock and admire it",
    desc: "it has been through things. so have you. nod at each other.",
    category: "outside",
    vibe: "geological kinship",
  },
  {
    id: "silence",
    emoji: "🤫",
    title: "enjoy three seconds of silence",
    desc: "then notice the fridge hum you forgot existed. that's also fine.",
    category: "senses",
    vibe: "negative space appreciation",
  },
  {
    id: "toast",
    emoji: "🍞",
    title: "watch toast cool down",
    desc: "it peaked. now it rests. you understand each other.",
    category: "tiny",
    vibe: "thermal decline meditation",
  },
  {
    id: "chair",
    emoji: "🪑",
    title: "sit in a different chair",
    desc: "same room. new throne. the shift is seismic and meaningless.",
    category: "weird",
    vibe: "furniture tourism",
  },
  {
    id: "flipaclip",
    emoji: "🎬",
    title: "open flipaclip and draw one frame",
    desc: "new project. blank canvas. animate one corner of something. close it. session over.",
    whisper: "secretly: your dozens of short loops keep growing.",
    category: "secret",
    vibe: "one frame counts if you squint",
  },
  {
    id: "corner-doodle",
    emoji: "✏️",
    title: "doodle in the vacant corner of a page",
    desc: "not a proper sketch. a corner invasion while you stare at nothing else.",
    whisper: "secretly: flipaclip fodder, frame by frame.",
    category: "secret",
    vibe: "peripheral creation",
  },
  {
    id: "animation-archive",
    emoji: "📼",
    title: "rewatch an old flipaclip loop",
    desc: "scroll your gallery. find one you forgot. don't post. don't fix. just remember.",
    whisper: "secretly: proof you've been drawing in vacant minutes forever.",
    category: "secret",
    vibe: "private film festival",
  },
  {
    id: "cursor-hello",
    emoji: "💻",
    title: "ask cursor to make a hello world",
    desc: "new folder. one prompt. watch files appear. understanding optional.",
    whisper: "secretly: netlify deploy + gh repo creation are already automated. zero stakes.",
    category: "secret",
    vibe: "accidental software",
  },
  {
    id: "git-spawn",
    emoji: "🌱",
    title: "spawn a git repo with a ridiculous name",
    desc: "empty readme. dumb title. push if you feel like it. the repo can nap forever.",
    whisper: "secretly: starting projects is a no-pressure reflex now.",
    category: "secret",
    vibe: "repository as pet rock",
  },
  {
    id: "deploy-nothing",
    emoji: "🚀",
    title: "deploy something tiny to netlify",
    desc: "one html file that says hi. or nothing. the internet can hold it gently.",
    whisper: "secretly: you've automated this. it's muscle memory.",
    category: "secret",
    vibe: "cloud-hosted whim",
  },
  {
    id: "terminal-mkdir",
    emoji: "⌨️",
    title: "mkdir a folder with a poetic name",
    desc: "open terminal. create soft-idea-7. cd in. leave. the folder waits patiently.",
    whisper: "secretly: future project seed, or forever empty. both valid.",
    category: "secret",
    vibe: "filesystem wish",
  },
  {
    id: "one-css-line",
    emoji: "🎨",
    title: "change one line of css somewhere",
    desc: "border-radius. a color. make something slightly rounder. close the tab.",
    whisper: "secretly: touch grass but for codebases.",
    category: "secret",
    vibe: "micro vandalism",
  },
  {
    id: "vibe-code",
    emoji: "🫧",
    title: "vibe-code for five minutes then walk away",
    desc: "tell the ai something vague and beautiful. let it cook. don't ship. don't even save.",
    whisper: "secretly: sometimes the prototype is the whole point.",
    category: "secret",
    vibe: "throwaway magic",
  },
];

export const activityMap = Object.fromEntries(
  builtInActivities.map((a) => [a.id, a]),
);

export function titleForId(id, community = []) {
  if (activityMap[id]) return activityMap[id].title;
  const found = community.find((a) => a.id === id);
  return found?.title ?? id;
}
